/*****************************************************************************
* 
* NXP Confidential Proprietary
*
* Copyright (c) 2014-2016 Freescale Semiconductor
* Copyright 2017 NXP 
* All Rights Reserved
*
******************************************************************************
*
* THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
****************************************************************************/
#ifndef APUDOWNSAMPLEUPSAMPLEGRAPHDEF_H
#define APUDOWNSAMPLEUPSAMPLEGRAPHDEF_H

#include <common_stringify_macros.h>

#define DOWNSAMPLE_UPSAMPLE_PI	APU_DOWNSAMPLE_UPSAMPLE
#define DOWNSAMPLE_UPSAMPLE_GN	XSTR(DOWNSAMPLE_UPSAMPLE_PI)

#define  DOWNSAMPLE_UPSAMPLE_IN			"INPUT"
#define  DOWNSAMPLE_UPSAMPLE_OUT_DOWN	"OUTPUT_DOWN"
#define  DOWNSAMPLE_UPSAMPLE_OUT_UP		"OUTPUT_UP"

#endif /* APUDOWNSAMPLEUPSAMPLEGRAPHDEF_H */

